* AWS Examples
This repository contains AWS Examples. Individual directories contains examples to individual AWS Services.
** CloudFormation
   - ~infrastructure.yaml~ ... nested stack that deploys basic infrastructure
     - ~vpc.yaml~          ... creates vpc 
     - ~subnets.yaml~      ... creates public and private subnets 
     - ~routing.yaml~      ... sets up routing between subnets
     - ~bastion.yaml~      ... creates bastion hosts in public subnet. Before creating this stack, make sure to create ssh key-pair
                               and update ~ImageId~ if needed.
*** Deployment guide
    Use ~awscli~ to deploy CloudFormation stacks. See install guide [[https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-install.html][here.]]
**** Prerequisities
    Create IAM User and attach Administrator policy (for simplicity, not recommended in production environment). Create access key and put into ~./aws/credentials~ file.
    #+BEGIN_SRC
    aws cloudformation package --template-file <nestedstack> --s3-bucket <s3_bucket_name> --output-template-file <packaged_nestedstack>
    aws cloudformation deploy --template-file <path/to/nested/stack/template> --stack-name <stack_name>  
    #+END_SRC 
