AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: Apache-2.0
Description: Master template that includes nested templates
Resources:
  VpcSubnets:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: vpcSubnets.yaml
  VpcRouting:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: vpcRouting.yaml
      Parameters: 
        PrimaryVpcId: !GetAtt VpcSubnets.Outputs.PrimaryVpcId
        PublicSubnetAZAId: !GetAtt VpcSubnets.Outputs.PublicSubnetAZAId
        PublicSubnetAZBId: !GetAtt VpcSubnets.Outputs.PublicSubnetAZBId
        PrivateSubnetAZAId: !GetAtt VpcSubnets.Outputs.PrivateSubnetAZAId
        PrivateSubnetAZBId: !GetAtt VpcSubnets.Outputs.PrivateSubnetAZBId
  Bastion:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: BastionV2.yaml
      Parameters:
        PrimaryVpcId: !GetAtt VpcSubnets.Outputs.PrimaryVpcId
        PublicSubnetAZAId: !GetAtt VpcSubnets.Outputs.PublicSubnetAZAId
        PublicSubnetAZBId: !GetAtt VpcSubnets.Outputs.PublicSubnetAZBId
    DependsOn: VpcRouting
