AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: Apache-2.0
Description: Master template that includes nested templates
Resources:
  VpcSubnets:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: vpcSubnets.yaml
  VpcRouting:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: vpcRouting.yaml
    DependsOn: VpcSubnets
  # BastionStack:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: bastion.yaml
  #   DependsOn: RoutingStack
