AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: Apache-2.0
Description: 'This template creates public and private subnets'
Resources:
Outputs:
  PublicSubnetRouteTableAZA:
    Description: Public Subnet Route Table Id
    Value: !Ref PublicSubnetRouteTableAZA
    Export:
      Name: PublicSubnetRouteTableAZAId
  PublicSubnetRouteTableAZB:
    Description: Public Subnet Route Table Id
    Value: !Ref PublicSubnetRouteTableAZB
    Export:
      Name: PublicSubnetRouteTableAZBId
  PrivateSubnetRouteTableAZA:
    Description: Private Subnet Route Table Id
    Value: !Ref PrivateSubnetRouteTableAZA
    Export:
      Name: PrivateSubnetRouteTableAZAId
  PrivateSubnetRouteTableAZB:
    Description: Private Subnet Route Table Id
    Value: !Ref PrivateSubnetRouteTableAZB
    Export:
      Name: PrivateSubnetRouteTableAZBId

