AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: Apache-2.0
Description: This template creates VPC
Resources:
  PrimaryVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: false
      InstanceTenancy: default
      Tags:
        - Key: Project
          Value: Alpha
        - Key: Owner
          Value: foo@bar.com
        - Key: VpcDesignation
          Value: Primary
Outputs:
  PrimaryVpcId:
    Description: Primary VPC Id
    Value: !Ref PrimaryVPC
    Export:
      Name: PrimaryVpcId
