AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: Apache-2.0
Description: Master template that includes nested templates
Parameters:
  ImageId:
    Description: AMI ID used for Bastion
    Type: AWS::EC2::Image::Id
    Default: ami-061392db613a6357b
  BastionKeyName:
    Description: bastion key name 
    Type: String
  PolicyTargetValue:
    Description: Scaling policy target value
    Type: String
  IpSpace:
    Description: > 
      Global IPv4 space for this infrastructure.
      All VPCs must be within this range
    Type: String
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
  VpcCidrBlock:
    Description: Vpc CIDR Block
    Type: String
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
  PublicSubnetsCidrBlocks:
    Description: Public Subnet Cidr Block list
    Type: String 
  PrivateSubnetsCidrBlocks:
    Description: Private Subnet Cidr Block list
    Type: String
Resources:
  VpcSubnets:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: vpcSubnets.yaml
      Parameters:
        IpSpace: !Ref IpSpace
        VpcCidrBlock: !Ref VpcCidrBlock
        PublicSubnetsCidrBlocks: !Ref PublicSubnetsCidrBlocks
        PrivateSubnetsCidrBlocks: !Ref PrivateSubnetsCidrBlocks
  VpcRouting:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: vpcRouting.yaml
      Parameters: 
        PrimaryVpcId: !GetAtt VpcSubnets.Outputs.PrimaryVpcId
        PublicSubnetAZAId: !GetAtt VpcSubnets.Outputs.PublicSubnetAZAId
        PublicSubnetAZBId: !GetAtt VpcSubnets.Outputs.PublicSubnetAZBId
        PrivateSubnetAZAId: !GetAtt VpcSubnets.Outputs.PrivateSubnetAZAId
        PrivateSubnetAZBId: !GetAtt VpcSubnets.Outputs.PrivateSubnetAZBId
  Bastion:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: BastionV2.yaml
      Parameters:
        PolicyTargetValue: !Ref PolicyTargetValue
        ImageId: !Ref ImageId
        KeyName: !Ref BastionKeyName
        PrimaryVpcId: !GetAtt VpcSubnets.Outputs.PrimaryVpcId
        PublicSubnetAZAId: !GetAtt VpcSubnets.Outputs.PublicSubnetAZAId
        PublicSubnetAZBId: !GetAtt VpcSubnets.Outputs.PublicSubnetAZBId
    DependsOn: VpcRouting
