AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: Apache-2.0
Description: This template creates Vpc
Parameters:
  IpSpace:
    Description: > 
      Global IPv4 space for this infrastructure.
      All VPCs must be within this range
    Type: String
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
  VpcCidrBlock:
    Description: Vpc CIDR Block
    Type: String
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
  PublicSubnetsCidrBlocks:
    Description: Public Subnet Cidr Block list
    Type: CommaDelimitedList
  PrivateSubnetsCidrBlocks:
    Description: Private Subnet Cidr Block list
    Type: CommaDelimitedList
Resources:
  PrimaryVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        - Key: Project
          Value: Alpha
        - Key: Owner
          Value: foo@bar.com
        - Key: VpcDesignation
          Value: Primary
  PublicSubnetAZA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select # us-west-2a
        - 0
        - !GetAZs
      CidrBlock: !Select
        - 0
        - !Ref PublicSubnetsCidrBlocks 
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Project
          Value: Alpha
        - Key: Owner
          Value: foo@bar.com
        - Key: SubnetType
          Value: Public
      VpcId: !Ref PrimaryVpc
  PublicSubnetAZB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select # us-west-2b
        - 1
        - !GetAZs
      CidrBlock: !Select
        - 1
        - !Ref PublicSubnetsCidrBlocks 
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Project
          Value: Alpha
        - Key: Owner
          Value: foo@bar.com
        - Key: SubnetType
          Value: Public
      VpcId: !Ref PrimaryVpc
  PrivateSubnetAZA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select # us-west-2a
        - 0
        - !GetAZs
      CidrBlock: !Select
        - 0
        - !Ref PrivateSubnetsCidrBlocks 
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Project
          Value: Alpha
        - Key: Owner
          Value: foo@bar.com
        - Key: SubnetType
          Value: Private
      VpcId: !Ref PrimaryVpc
  PrivateSubnetAZB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select # us-west-2b
        - 1
        - !GetAZs
      CidrBlock: !Select
        - 1
        - !Ref PrivateSubnetsCidrBlocks 
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Project
          Value: Alpha
        - Key: Owner
          Value: foo@bar.com
        - Key: SubnetType
          Value: Private
      VpcId: !Ref PrimaryVpc
Outputs:
  PrimaryVpcId:
    Description: Primary Vpc Id
    Value: !Ref PrimaryVpc
    Export:
      Name: PrimaryVpcId
  PublicSubnetAZAId:
    Description: Public Subnet Id
    Value: !Ref PublicSubnetAZA
    Export:
      Name: PublicSubnetAZAId
  PublicSubnetAZBId:
    Description: Public Subnet Id
    Value: !Ref PublicSubnetAZB
    Export:
      Name: PublicSubnetAZBId
  PrivateSubnetAZAId:
    Description: Private Subnet Id
    Value: !Ref PrivateSubnetAZA
    Export:
      Name: PrivateSubnetAZAId
  PrivateSubnetAZBId:
    Description: Private Subnet Id
    Value: !Ref PrivateSubnetAZB
    Export:
      Name: PrivateSubnetAZBId
  IpSpace:
    Description: Global IPv4 Space
    Value: !Ref IpSpace 
    Export:
      Name: IpSpace 